/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RRoomIdImport } from './routes/r.$roomId'

// Create Virtual Routes

const JoinLazyImport = createFileRoute('/join')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const JoinLazyRoute = JoinLazyImport.update({
  path: '/join',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/join.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RRoomIdRoute = RRoomIdImport.update({
  path: '/r/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinLazyImport
      parentRoute: typeof rootRoute
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/join': typeof JoinLazyRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/join': typeof JoinLazyRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/join': typeof JoinLazyRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/r/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/r/$roomId'
  id: '__root__' | '/' | '/join' | '/r/$roomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  JoinLazyRoute: typeof JoinLazyRoute
  RRoomIdRoute: typeof RRoomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  JoinLazyRoute: JoinLazyRoute,
  RRoomIdRoute: RRoomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/join",
        "/r/$roomId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/join": {
      "filePath": "join.lazy.tsx"
    },
    "/r/$roomId": {
      "filePath": "r.$roomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
